### ISSUE TITLE
How to change default font

### ISSUE THREAD

**Issue by dattasaurabh82** [alloydwhitlock/huey#1]
Hi there, 
Awesome lib. 
Question is if I wanted to change the default font, where to change them. 
Can you please guide me with a bit more details?

**Comment by alloydwhitlock** [comment]
You can add specific SASS elements to `assets/css/base/base.scss`, where `$family-primary` is likely what you want. There is some information in the README.md that points to this, but also check this out. https://bulma.io/documentation/customize/variables/
